services:
  app:
    build: .

    container_name: marketplacex-app

    ports:
      - "3000:3000"

    env_file:
      - .env.docker

    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine

    container_name: marketplacex-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brij@09876
      POSTGRES_DB: marketplacex

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
