services:
  postgres:
    image: postgres:16

    container_name: marketplacex-postgres

    environment:
      POSTGRES_DB: marketplacex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brij@09876

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: